# Generated by Django 3.0.9 on 2020-08-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('isbn', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('year_published', models.IntegerField()),
            ],
        ),
    ]
