# Generated by Django 3.0.9 on 2020-08-04 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_librarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='librarian',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraryapp.Librarian'),
        ),
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.Library'),
        ),
    ]
